// <auto-generated />
namespace eVisa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class change_children : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_children));
        
        string IMigrationMetadata.Id
        {
            get { return "201607010250358_change_children"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
